apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-images
spec:
  validationFailureAction: Enforce
  rules:
    - name: verify-signatures
      match:
        any:
          - resources:
              kinds: ["Pod"]
      verifyImages:
        - imageReferences: ["ghcr.io/Pinak/*"]
          attestors:
            - entries:
                - keys:
                    secret:
                      name: cosign-pubkey
                      namespace: security
          attestations:
            - predicateType: https://slsa.dev/provenance/v1
